repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        name: Run Ruff on Lib/test/
        args: [--exit-non-zero-on-fix]
        files: ^Lib/test/
      - id: ruff
        name: Run Ruff on Argument Clinic
        args: [--exit-non-zero-on-fix, --config=Tools/clinic/.ruff.toml]
        files: ^Tools/clinic/|Lib/test/test_clinic.py

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
        exclude: ^Lib/test/test_tomllib/
      - id: check-yaml
      - id: end-of-file-fixer
        types: [python]
        exclude: Lib/test/tokenizedata/coding20731.py
      - id: trailing-whitespace
        types_or: [c, inc, python, rst]

  - repo: local
    hooks:
      - id: python-file-whitespace
        name: "Check Python file whitespace"
        entry: 'python Tools/patchcheck/reindent.py --nobackup --newline LF'
        language: 'system'
        types: [python]
        exclude: '^(Lib/test/tokenizedata/|Tools/c-analyzer/cpython/_parser).*$'

  - repo: local
    hooks:
      - id: c-file-whitespace
        name: "Check C file whitespace"
        entry: "python Tools/patchcheck/untabify.py"
        language: "system"
        types_or: ['c', 'c++']
        # Don't check the style of vendored libraries
        exclude: |
          (?x)^(
            Modules/_decimal/.*
            | Modules/libmpdec/.*
            | Modules/expat/.*
          )$

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.6.8
    hooks:
      - id: sphinx-lint
        args: [--enable=default-role]
        files: ^Doc/|^Misc/NEWS.d/next/
        types: [rst]
        require_serial: true

  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
