[build]
    base = "Doc/"
    command = "make html"
    publish = "build/html"
    # Do not trigger netlify builds if docs were not changed.
    # Changed files should be in sync with `.github/workflows/doc.yml`
    ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../netlify.toml"

[build.environment]
  PYTHON_VERSION = "3.8"
  IS_DEPLOYMENT_PREVIEW = "true"
