name: TestsMSI

on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - '3.*'
    paths:
    - 'Tools/msi/**'
    - '.github/workflows/build_msi.yml'
  pull_request:
    branches:
    - 'main'
    - '3.*'
    paths:
    - 'Tools/msi/**'
    - '.github/workflows/build_msi.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Windows Installer
    runs-on: windows-latest
    timeout-minutes: 60
    strategy:
      matrix:
        type: [x86, x64, arm64]
    steps:
    - uses: actions/checkout@v4
    - name: Build CPython installer
      run: .\Tools\msi\build.bat --doc -${{ matrix.type }}
