name: Update GH projects

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  add-to-project:
    name: Add to the Release and Deferred Blocker project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/python/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: release-blocker, deferred-blocker
          label-operator: OR
